apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp3dashboard-gustavocunha
  namespace: gustavocunha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      containers:
        - name: dashboard
          image: gustavofcunha/dashboard:v1
          ports:
            - containerPort: 5000