apiVersion: v1
kind: Service
metadata:
  name: tp3dashboard-gustavocunha
  namespace: gustavocunha
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 45689
  selector:
    app: dashboard